# Dependabot configuration for automated dependency updates
# Documentation: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "rdrlabs/developers"
    allow:
      # Only allow updates to production dependencies
      - dependency-type: "production"
    ignore:
      # Major version updates for critical packages
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    groups:
      # Group all patch updates together
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      # Group testing library updates
      testing:
        patterns:
          - "@testing-library/*"
          - "vitest"
          - "@vitest/*"
      # Group ESLint related updates
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
      # Group Tailwind CSS updates
      tailwind:
        patterns:
          - "tailwindcss*"
          - "@tailwindcss/*"
      # Group shadcn/ui related updates
      shadcn:
        patterns:
          - "@radix-ui/*"
          - "class-variance-authority"
          - "clsx"
          - "tailwind-merge"
      # Group Fumadocs updates
      fumadocs:
        patterns:
          - "fumadocs-*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "rdrlabs/developers"

  # Security updates configuration
  # Security updates are enabled by default for all ecosystems
  # They are created immediately when a vulnerability is detected
  # regardless of the schedule defined above
