[build]
  command = "npm --version && node --version && npm install && npm run build"
  publish = "out"
  ignore = "./.netlify/ignore-build.sh"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    # Prevent clickjacking attacks
    X-Frame-Options = "DENY"
    
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Enable XSS filter (legacy support)
    X-XSS-Protection = "1; mode=block"
    
    # Control referrer information
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Limit browser features
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), accelerometer=(), gyroscope=()"
    
    # Content Security Policy - merged to include both upstash and fonts
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.supabase.co https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: blob: https:; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' *.supabase.co wss://*.supabase.co https://*.supabase.co https://*.upstash.io; frame-src 'none'; frame-ancestors 'none'; object-src 'none'; base-uri 'self'; form-action 'self';"
    
    # Enable HTTPS only (HSTS) - 1 year
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[redirects]]
  from = "/admin"
  to = "/"
  status = 301
  force = true