[build]
  command = "npm ci && npm run build"
  publish = "build/client"
  
[build.environment]
  NODE_VERSION = "20"
  
# Build processing optimizations
[build.processing]
  skip_processing = false

# Enable build plugins for optimization
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
# Functions disabled for SPA mode
# [functions]
#   directory = "build/server"
#   node_bundler = "esbuild"

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    "X-Frame-Options" = "DENY"
    "X-Content-Type-Options" = "nosniff"
    "X-XSS-Protection" = "1; mode=block"
    "Referrer-Policy" = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# SPA redirects - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 5173
  publish = "build/client"
  autoLaunch = false