[build]
  command = "npm ci && npm run build"
  publish = "build/client"
  
[build.environment]
  NODE_VERSION = "18"
  NETLIFY_SKIP_CACHE = "true"
  
[functions]
  directory = "build/server"
  node_bundler = "esbuild"

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    "X-Frame-Options" = "DENY"
    "X-Content-Type-Options" = "nosniff"
    "X-XSS-Protection" = "1; mode=block"
    "Referrer-Policy" = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 5173
  publish = "build/client"
  autoLaunch = false