-- Update the pending_auth_sessions table to remove the default UUID generation
-- This allows the application to provide cryptographically secure tokens using crypto.randomUUID()

-- Remove the default value from session_token column
ALTER TABLE pending_auth_sessions 
ALTER COLUMN session_token DROP DEFAULT;

-- Add a comment explaining the change
COMMENT ON COLUMN pending_auth_sessions.session_token IS 'Session token generated by the application using crypto.randomUUID() for enhanced security';